import Application from "@/components/Application/Application";
import Alert from "@/components/custom-ui/Alert/Alert";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { MembershipApplicationType } from "@/types/Membership.type";
import { fetchApplicationById } from "@/utils/api/admin/fetchApplicationById";
import { getDateWithTime } from "@/utils/helper";
import { Printer } from "iconoir-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";

const MembershipApplicationPrint: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [applicationData, setApplicationData] =
    useState<MembershipApplicationType | null>(null);
  const { id } = useParams();

  const fetchApplicationData = async (id: string) => {
    try {
      setLoading(true);
      const data = await fetchApplicationById(id);
      if (!data) return;
      console.log(data);
      setApplicationData(data);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    document.body.style.overflow = "visible";
    if (id && !applicationData) {
      fetchApplicationData(id);
    }
  }, []);

  return (
    <div className="border-2 border-solid flex flex-col max-w-2xl bg-card mx-auto rounded-sm overflow-hidden">
      <header className="px-8 py-4 flex gap-4 justify-between p-2 border-b">
        <div className="h-11">
          <Link className="print:hidden" to="/">
            <img
              className="h-full w-auto"
              src="/navbar-banner.svg"
              alt="NIT AP Alumni"
            />
          </Link>
          <img
            className="h-full w-auto hidden print:block"
            src="/navbar-banner.svg"
            alt="NIT AP Alumni"
          />
        </div>
        <div>
          <ul>
            <li className="text-sm">
              E-mail:{" "}
              <a href="mailto://alumnicell@nitap.ac.in">
                alumnicell@nitap.ac.in
              </a>
            </li>
          </ul>
        </div>
      </header>
      {loading ? (
        <div className="px-6 py-4 flex justify-center items-center">
          <Spinner />
        </div>
      ) : applicationData ? (
        <>
          <main className="">
            <Application applicationData={applicationData} />
          </main>
          <footer className="px-8 py-4 border-t border-solid">
            <p className="text-sm mb-2">
              To apply for a life membership, submit this form along with a copy
              of receipt of payment of Membership Fee of Rs. 500 to the below
              mentioned account to Alumni cell.
            </p>
            <div className="w-fit print:hidden mb-2">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Alumni cell account details</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>Account name</TableCell>
                    <TableCell>ALUMNINIT Arp</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Account Number</TableCell>
                    <TableCell>33989 984029</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>IFSC</TableCell>
                    <TableCell>SBIN0009535</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
            <p className="text-sm">
              This application was autogenerated from NIT Arunachal Pradesh
              Alumni Portal at {getDateWithTime(applicationData?.created_at)}
            </p>
            <div className="print:hidden py-4">
              <Button variant="outline" onClick={() => print()}>
                <Printer />
                Print
              </Button>
            </div>
          </footer>
        </>
      ) : (
        <div className="px-8 py-4">
          <Alert severity="error">Invalid application id</Alert>
        </div>
      )}
    </div>
  );
};

export default MembershipApplicationPrint;
